# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CountWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(746, 609)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NumberLayout = QtWidgets.QGridLayout()
        self.NumberLayout.setObjectName("NumberLayout")
        self.horizontalLayout.addLayout(self.NumberLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LanguageComboBox = QtWidgets.QComboBox(Dialog)
        self.LanguageComboBox.setObjectName("LanguageComboBox")
        self.LanguageComboBox.addItem("")
        self.LanguageComboBox.addItem("")
        self.verticalLayout.addWidget(self.LanguageComboBox)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.ScanIntervalSlider = QtWidgets.QSlider(Dialog)
        self.ScanIntervalSlider.setMinimum(100)
        self.ScanIntervalSlider.setMaximum(5000)
        self.ScanIntervalSlider.setProperty("value", 500)
        self.ScanIntervalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.ScanIntervalSlider.setObjectName("ScanIntervalSlider")
        self.horizontalLayout_2.addWidget(self.ScanIntervalSlider)
        self.InternalText = QtWidgets.QLabel(Dialog)
        self.InternalText.setObjectName("InternalText")
        self.horizontalLayout_2.addWidget(self.InternalText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.ScanBtn = QtWidgets.QPushButton(Dialog)
        self.ScanBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.ScanBtn.setCheckable(True)
        self.ScanBtn.setObjectName("ScanBtn")
        self.verticalLayout.addWidget(self.ScanBtn)
        self.RandomPickBtn = QtWidgets.QPushButton(Dialog)
        self.RandomPickBtn.setObjectName("RandomPickBtn")
        self.verticalLayout.addWidget(self.RandomPickBtn)
        self.ResetBtn = QtWidgets.QPushButton(Dialog)
        self.ResetBtn.setObjectName("ResetBtn")
        self.verticalLayout.addWidget(self.ResetBtn)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Form"))
        self.LanguageComboBox.setItemText(0, _translate("Dialog", "中文"))
        self.LanguageComboBox.setItemText(1, _translate("Dialog", "英文"))
        self.label.setText(_translate("Dialog", "间隔"))
        self.InternalText.setText(_translate("Dialog", "ms"))
        self.ScanBtn.setText(_translate("Dialog", "浏览"))
        self.RandomPickBtn.setText(_translate("Dialog", "挑选"))
        self.ResetBtn.setText(_translate("Dialog", "重置"))
