# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CountWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(746, 609)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.NumberLayout = QtWidgets.QGridLayout()
        self.NumberLayout.setObjectName("NumberLayout")
        self.horizontalLayout.addLayout(self.NumberLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.LanguageCombox = QtWidgets.QComboBox(Dialog)
        self.LanguageCombox.setObjectName("LanguageCombox")
        self.LanguageCombox.addItem("")
        self.LanguageCombox.addItem("")
        self.verticalLayout.addWidget(self.LanguageCombox)
        self.ScanBtn = QtWidgets.QPushButton(Dialog)
        self.ScanBtn.setObjectName("ScanBtn")
        self.verticalLayout.addWidget(self.ScanBtn)
        self.RandomPickBtn = QtWidgets.QPushButton(Dialog)
        self.RandomPickBtn.setObjectName("RandomPickBtn")
        self.verticalLayout.addWidget(self.RandomPickBtn)
        self.ClearBtn = QtWidgets.QPushButton(Dialog)
        self.ClearBtn.setObjectName("ClearBtn")
        self.verticalLayout.addWidget(self.ClearBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(1, 1)

        self.retranslateUi(Dialog)
        self.RandomPickBtn.clicked.connect(Dialog.close)
        self.ClearBtn.clicked.connect(Dialog.close)
        self.ScanBtn.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Form"))
        self.LanguageCombox.setItemText(0, _translate("Dialog", "中文"))
        self.LanguageCombox.setItemText(1, _translate("Dialog", "英文"))
        self.ScanBtn.setText(_translate("Dialog", "浏览"))
        self.RandomPickBtn.setText(_translate("Dialog", "挑选"))
        self.ClearBtn.setText(_translate("Dialog", "清除"))
